BIGSCHOOL/Controllers/Courses_2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIGSCHOOL.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
// sử dụng cho lấy user id
//using Microsoft.AspNet.Identity;
//using Microsoft.AspNet.Identity.Owin;

namespace BIGSCHOOL.Controllers
{
    public class Courses_2Controller : Controller
    {
        

        BigSchoolContext db = new BigSchoolContext();
        // GET: Courses_2
        public ActionResult Index()
        {
            
            var upcomingCourse = db.Courses.Where(p => p.DateTime > DateTime.Now).OrderBy(p => p.DateTime).ToList();
            foreach (Course i in upcomingCourse)
            {
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(i.LectureId);
                i.Name = user.Name;

            }
            return View(upcomingCourse);
        }

        public ActionResult Create()
        {
            Course obj_course = new Course();
            //ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            obj_course.ListCategory = db.Categories.ToList();
            return View(obj_course);
        }
        [Authorize]
        [HttpPost]

        public ActionResult Create(Course obj_course)
        {

            //
            ModelState.Remove("LectureId");
            if (!ModelState.IsValid)
            {
                obj_course.ListCategory = db.Categories.ToList();
                return View("Create", obj_course);
            }
            // lấy login user id
            ApplicationUser user = new ApplicationUser();
            user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            obj_course.LectureId = user.Id;

            // add vào csdl
            db.Courses.Add(obj_course);
            db.SaveChanges();


            //ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Attending()
        {
            BigSchoolContext context = new BigSchoolContext();
            ApplicationUser currentUser = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>()
                .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            var listAttendances = context.Attendances.Where(p => p.Attendee == currentUser.Id).ToList();
            var courses = new List<Course>();
            foreach(Attendance temp in listAttendances)
            {
                Course objCourse = temp.Course;
                objCourse.LectureName = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(objCourse.LectureId).Name;
                courses.Add(objCourse);
                
            }
            return View(courses);
        }

        public ActionResult Mine()
        {
            
            ApplicationUser currentUser = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>()
                .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            BigSchoolContext context = new BigSchoolContext();
            // var listAttendances = context.Attendances.Where(p => p.Attendee == currentUser.Id).ToList();
            //var courses = new List<Course>();
            var courses = context.Courses.Where(c => c.LectureId == currentUser.Id
            && c.DateTime > DateTime.Now).ToList();

            foreach (Course i in courses)
            {
                i.LectureName = currentUser.Name; 

            }
            return View(courses);
        }

        public ActionResult LectureIamGoing()
        {
            ApplicationUser currentUser =
            System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>()
            .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            BigSchoolContext context = new BigSchoolContext();
            //danh sách giảng viên được theo dõi bởi người dùng (đăng nhập) hiện tại
            var listFollwee = context.Followings.Where(p => p.FollowerId ==
            currentUser.Id).ToList();
            //danh sách các khóa học mà người dùng đã đăng ký
            var listAttendances = context.Attendances.Where(p => p.Attendee ==
            currentUser.Id).ToList();
            var courses = new List<Course>();
            foreach (var course in listAttendances)
            {
                foreach (var item in listFollwee)
                {
                    if (item.FolloweeId == course.Course.LectureId)
                    {
                        Course objCourse = course.Course;
                        objCourse.LectureName =
                       System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>()
                        .FindById(objCourse.LectureId).Name;
                        courses.Add(objCourse);
                    }
                }

            }
            return View(courses);
        }


    }
}

BIGSCHOOL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using BIGSCHOOL.Models;

namespace BIGSCHOOL.Controllers
{
    public class HomeController : Controller
    {
        BigSchoolContext db = new BigSchoolContext();
        

        [Authorize]
        public ActionResult Index()
            
        {
 
            var upcommingCourse = db.Courses.Where(p => p.DateTime >
           DateTime.Now).OrderBy(p => p.DateTime).ToList();
            //lấy user login hiện tại 
            var userID = User.Identity.GetUserId();
            foreach (Course i in upcommingCourse)
            {
                //tìm Name của user từ lectureid
                ApplicationUser user =
                System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>(
                ).FindById(i.LectureId);
                i.Name = user.Name;
                //lấy ds tham gia khóa học 
                if (userID != null)
                {
                    i.isLogin = true;
                    //ktra user đó chưa tham gia khóa học 
                    Attendance find = db.Attendances.FirstOrDefault(p =>
                    p.CourseID == i.Id && p.Attendee == userID);
                    if (find == null)
                        i.isShowGoing = true;
                    //ktra user đã theo dõi giảng viên của khóa học ? 
                    Following findFollow = db.Followings.FirstOrDefault(p =>
                    p.FollowerId == userID && p.FolloweeId == i.LectureId);
                    if (findFollow == null)
                        i.isShowFollow = true;
                }
            }
            return View(upcommingCourse);
        }




       // [Authorize]
        public ActionResult Index2()

        {

            var upcommingCourse = db.Courses.Where(p => p.DateTime >
           DateTime.Now).OrderBy(p => p.DateTime).ToList();
            //lấy user login hiện tại 
            var userID = User.Identity.GetUserId();
            foreach (Course i in upcommingCourse)
            {
                //tìm Name của user từ lectureid
                ApplicationUser user =
                System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>(
                ).FindById(i.LectureId);
                i.Name = user.Name;
                //lấy ds tham gia khóa học 
                if (userID != null)
                {
                    i.isLogin = true;
                    //ktra user đó chưa tham gia khóa học 
                    Attendance find = db.Attendances.FirstOrDefault(p =>
                    p.CourseID == i.Id && p.Attendee == userID);
                    if (find != null)
                        i.isShowGoing = true;
                    //ktra user đã theo dõi giảng viên của khóa học ? 
                    Following findFollow = db.Followings.FirstOrDefault(p =>
                    p.FollowerId == userID && p.FolloweeId == i.LectureId);
                    if (findFollow == null)
                        i.isShowFollow = true;
                }
            }
            return View(upcommingCourse);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BIGSCHOOL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BIGSCHOOL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BIGSCHOOL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<p>
    @Html.ActionLink("Create New", "Create","Courses_2")
</p>

@using BIGSCHOOL.Models;
@model  IEnumerable<BIGSCHOOL.Models.Course>
@{ ViewBag.Title = "Home Page"; }

<h3> Danh sách khóa học sắp tới</h3>
<div class="row">
    <ul class="course">
        @foreach (var course in Model)
        {
            <li>
                <div class="date">
                    <div class="month">
                        @*@course.DateTime.ToString("dd/MM/yyyy HH:mm")*@
                        @course.DateTime.ToString("MM")

                    </div>
                    <div class="day">
                        @course.DateTime.ToString("dd")

                    </div>

                </div>
                <div class="detail">
                    <span class="lecture">
                        @course.Name
                        @if (course.isLogin)
                        {
                            if (course.isShowFollow)
                            {
                                <button data-user-id="@course.LectureId" class="btn btn-default btn-sm js-tongle-follow">  Theo dõi?</button>

                            }
                            else
                            {
                                <button data-user-id="@course.LectureId" class="btn btn-success btn-sm js-tongle-follow">  Đang theo dõi</button>

                            }



                        }


                    </span>
                    <br />
                    <span class="category">
                        @course.Category.Name -- @course.Id
                        @if (course.isLogin)
                        {
                            if (course.isShowGoing)
                            {
                                <button data-course-id="@course.Id" class="btn btn-default btn-sm js-tongle-attendance">Tham gia?</button>


                            }
                            else
                            {
                                <button data-course-id="@course.Id" class="btn btn-success btn-sm js-tongle-attendance">Đã tham gia</button>

                            }

                        }


                    </span>



                </div>

            </li>
        }
    </ul>




    @section scripts{
        <script>
           
            $(".js-tongle-attendance").click(function (e) {
                var button = $(e.target);
                $.post("/api/Attendances", { Id: button.attr("data-course-id") })
                    .done(function (result) {
                        if (result == "cancel") {
                            alert("Hủy bỏ tham gia khóa học!!")
                            button
                                .removeClass("btn-success")
                                .addClass("btn-default")
                                .text("Tham gia?");
                        } else {
                            alert("Tham gia khóa học thành công <3!")
                            button
                                .removeClass("btn-default")
                                .addClass("btn-success")
                                .text("Đã tham gia");
                        }
                    }).fail(function () {
                        alert("Something fail");
                    });
            });
            $(".js-tongle-follow").click(function (e) {
                var button = $(e.target);
                var followee = button.attr("data-user-id");
                $.post("/api/Following", { FolloweeId: button.attr("data-user-id") })
                    .done(function (result) {
                        if (result == "cancel") {
                            $('.js-tongle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-success")
                                        .addClass("btn-default")
                                        .text("Theo dõi?");
                                }
                            });
                            alert("Hủy bỏ theo dõi !! ")
                        } else {
                            $('.js-toggle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-default")
                                        .addClass("btn-success")
                                        .text("Đang theo dõi <3");
                                }
                            });
                            alert("Theo dõi thành công <3")
                        }
                    }).fail(function () {
                       @* alert("Something fail");*@
                         alert("Không thể tự theo dõi chính mình");
                    });
            });
               
        </script>
    }

   

</div>

BIGSCHOOL/Views/Home/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="panel panel-success">
    <div class="panel-heading">
        <strong class="panel-title">DANH SÁCH KHÓA HỌC SẮP TỚI</strong>
    </div>
    <table class="table table-hover table-condensed">
        <thead class="bg-danger">
            <tr>
                <th>Thời gian bắt đầu</th>
                <th>Giảng viên</th>
                <th>Tên khóa học</th>
                <th>Địa điểm</th>
                <th>Trạng thái</th>
                <th>Tham gia</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>@item.DateTime.ToString("dd/MM/yyyy HH:mm")</td>
                <td>@item.Name</td>
                <td>@item.Category.Name</td>
                <td>@item.Place</td>
                <td>
                    @if (item.isLogin)
                    {
                        if (item.isShowFollow)
                        {
                            <button data-user-id="@item.LectureId" class="btn btn-default btn-sm js-tongle-follow">  Theo dõi?</button>

                        }
                        else
                        {
                            <button data-user-id="@item.LectureId" class="btn btn-success btn-sm js-tongle-follow">  Đang theo dõi</button>

                        }



                    }
                </td>

                <td>
                    @if (item.isLogin)
                    {
                        if (!item.isShowGoing)
                        {
                            <button data-course-id="@item.Id" class="btn btn-default btn-sm js-tongle-attendance">Tham gia?</button>


                        }
                        else
                        {
                            <button data-course-id="@item.Id" class="btn btn-success btn-sm js-tongle-attendance">Đã tham gia</button>

                        }

                    }

                </td>



            </tr>

            }


        </tbody>
    </table>





    @section scripts{
        <script>

            $(".js-tongle-attendance").click(function (e) {
                var button = $(e.target);
                $.post("/api/Attendances", { Id: button.attr("data-course-id") })
                    .done(function (result) {
                        if (result == "cancel") {
                            alert("Hủy bỏ tham gia khóa học!!")
                            button
                                .removeClass("btn-success")
                                .addClass("btn-default")
                                .text("Tham gia?");
                        } else {
                            alert("Tham gia khóa học thành công!!")
                            button
                                .removeClass("btn-default")
                                .addClass("btn-success")
                                .text("Đã tham gia");
                        }
                    }).fail(function () {
                        alert("Something fail");
                    });
            });
           @* $(".js-tongle-follow").click(function (e) {
                var button = $(e.target);
                var followee = button.attr("data-user-id");
                $.post("/api/Following", { FolloweeId: button.attr("data-user-id") })
                    .done(function (result) {
                        if (result == "cancel") {
                            $('.js-tongle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-success")
                                        .addClass("btn-default")
                                        .text("Theo dõi?");
                                }
                            });
                            alert("Hủy bỏ theo dõi !! ")
                        } else {
                            $('.js-toggle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-default")
                                        .addClass("btn-success")
                                        .text("Đang theo dõi <3");
                                }
                            });
                            alert("Theo dõi thành công <3")
                        }
                    }).fail(function () {
                       
                         alert("Không thể tự theo dõi chính mình");
                    });
            });*@



            $(".js-tongle-follow").click(function (e) {
                var button = $(e.target);
                var followee = button.attr("data-user-id");
                $.post("/api/Following", { FolloweeId: button.attr("data-user-id") })
                    .done(function (resp) {
                        if (resp == "cancel") {
                            $('.js-tongle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-success")
                                        .addClass("btn-default")
                                        .text("Theo dõi?");
                                }
                            });
                            alert("Bỏ theo dõi thành công")
                        }
                        else {
                            $('.js-tongle-follow').each(function (i, obj) {
                                if ($(this).attr('data-user-id') == followee) {
                                    $(this).removeClass("btn-default")
                                        .addClass("btn-success")
                                        .text("Đang theo dõi");
                                }
                            });
                            alert("Theo dõi thành công")
                        }
                    })
                    .fail(function () {
                        alert("Không thể tự theo dõi chính mình!");
                    })
            })
            

        </script>
    }

</div>